name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh   # Create the .ssh directory if it doesn't exist

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Set permissions for the private key

      - name: Set up SSH
        run: |
          eval "$(ssh-agent -s)"   # Start the SSH agent
          ssh-add ~/.ssh/id_rsa     # Add the private key to the agent

      - name: Build and push Docker image
        run: |
          docker build -t my-node-service .
          docker save my-node-service | gzip > my-node-service.tar.gz
          scp my-node-service.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}

      - name: Deploy on remote server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            docker load < my-node-service.tar.gz
            docker run -d -p 80:3000 my-node-service
          EOF
